### ISSUE TITLE
Update library dependencies

### ISSUE THREAD

**Issue by andys8** [davidchase/ramtuary#16]
Great REPL combined with `ramda-fantasy` and `Sanctuary`. I saw the dependencies are a little outdated:
```
    "ramda": "0.17.1",
    "ramda-fantasy": "0.4.0",
    "sanctuary": "0.7.0"
```
Currently Ramda is at `0.23.0`, Ramda-Fantasy at `0.7.0` and Sanctuary at `0.11.1`. Would be great to update and publish. Thank you.

**Comment by davidchase** [comment]
@andys8 will do thanks for the nudge... i still am amazed at people still using this repl... i

**Comment by davidchase** [comment]
after further looking at this issue, i realized that i actually pull ramda + ramda-fantasy and sanctuary + tcomb from the [cdn and always select latest](https://github.com/davidchase/ramtuary/blob/gh-pages/index.html#L97-L100)

the package json is for internal code for the repl rather than the user's interaction with it

so i think this issue can be closed

**Comment by andys8** [comment]
Great. Thank you for investigating.
